### ISSUE TITLE
Gestion des touches ne doit pas se faire avec un else !!

### ISSUE THREAD

**Issue by micbuffa** [JohnCarmack/kawaigame#24]
L'ergonomie n'est pas correcte si vous gérez les appuis et relâchement des touches. Les diagonales ne marchent pas prises en compte, c'est exprès ? Je trouve le feeling "bizarre". Perso, je virerai tous les "else" des écouteurs keyup et keydown + j'utiliserai une sprite sheet avec 8 directions, pour un feeling plus "nerveux" dans le jeu final. Là, le perso fait des trucs bizarres quand on essaie de faire une diagonale. On appuie sur flèche bas, il descend. En même temps on appuie sur flèche droite, il se passe un espèce de temps d'arrêt. Le contrôle n'est pas "smooth"... Je ne sais pas si vous voyez ce que je veux dire...

**Comment by micbuffa** [comment]
En fait, j'ai bien isolé le soucis: voici un exemple: 1) on descend, fleche en bas enfoncé. 2) Tout en gardant fleche en bas enfoncée, on appuie sur fleche gauche, le perso tourne à gauche horizontalement. Normal... 3) On relache fleche en haut (fleche à gauche est toujours enfoncée et le perso est en train de marcher vers la gauche) -> Le perso s'arrête puis repart. C'est ce temps d'arrêt qui est gênant. On dirait que quand vous relachez haut, vous mettez DIR à une valeur nulle et il faut encore un tour pour remettre DIR à la bonne valeur...

**Comment by camillou11** [comment]
Bonjour,

En effet nous avions déjà identifiés le problème. Nous allons le corriger
rapidement.
Merci pour votre retour.

Cordialement,
Camille Bovin
