### ISSUE TITLE
Code serveur app.js doit utiliser des variables d'environnement pour PORT et IP

### ISSUE THREAD

**Issue by micbuffa** [JohnCarmack/kawaigame#25]
Important: use process.env.PORT as the port and process.env.IP as the host in your scripts!

Sinon, ça ne pourra pas marcher le run sur c9.io (rappel: pour lancer une app nodeJS sur c9.io, il faut double cliquer le fichier du serveur et cliquer le bouton run ou utiliser le menu right click).

// Config
var PORT = process.env.PORT,
    addrIP = process.env.IP;

puis faire:

// launch the http server on given port
server.listen(PORT || 3000, addrIP || "0.0.0.0", function(){
  var addr = server.address();
  console.log("Game server listening at", addr.address + ":" + addr.port);
});

Dans le terminal de C9 penser quand vous faites des modifs à bien faire:
git add sur les fichiers modifiés
git commit -m "decription des modifs"
git push

et quand vous revenez dessus pour travailler, toujours commencer par un "git pull"

Trucs de base, je sais...

**Comment by Desiderius77** [comment]
Bonjour Michel

Merci de tes commentaires sur le projet Kawaigame !

Coté GPS, les étudiants m'ont dit qu'ils ont été contactés par les 
Niçois hier à 1 h du matin !
Grâce à toi je suppose !

En tout cas, ils se sont distribués les taches et cela a l'air de 
repartir sur de bons pieds

Je démarre également une série de cours avec les M1 MIAGE Initiaux dans 
lesquels je dois leur apprendre HTML5.

Je suppose qu'ils ne peuvent plus s’inscrire à ton MOOC Part 1 ?

Je peux encore avec mon compte mais je ne sais pas comment leur donner 
un support de cours  ?

Au pire, je reprendrais mon vieux cours en l'illustrant avec des pages 
de ton MOOC

Didier

**Comment by micbuffa** [comment]
Je pense que les élèves peuvent encore s'inscrire mais les exos ne seront
plus faisables (les quizzes) et le forum est au ralenti. Je ne fais plus de
support non plus. J'ai bien expliqué les choses au projet GPS. On prévoit
une visio mardi prochain. J'essaierai d'en faire une un soir avec les
étudiants. Désolé pour hier...

Le mer. 27 janv. 2016 à 09:10, Desiderius77 notifications@github.com a
écrit :

**Comment by JohnCarmack** [comment]
This issue was done in #19 8 days ago. Merci.
