### ISSUE TITLE
Je ne sais pas ce que vous faites. Pas de compte rendu de réunion etc.

### ISSUE THREAD

**Issue by micbuffa** [JohnCarmack/kawaigame#66]
Je ne devine où vous en êtes que en voyant les issues/pull requests, mais depuis le début du projet quasiment je n'ai rien vu, je n'ai pas eu de compte rendu de vos réunions à Evry, je ne sais pas ce que vous faites, si ça marche ou pas, si vous galérez ou pas etc. Ce serait sympa de me tenir au courant... :-)

**Comment by JohnCarmack** [comment]
Bonjour monsieur,

Les comptes rendu de réunion sont dans la partie "wiki -> compte rendu", c'est le contrat depuis le début, nous devons tout tracer et  tout est inscrit dessus. 
Je vous ai donné un lien en réponse à votre commentaire sur mon pull request sur les rooms qui est celui-ci : 
https://kawaigame-johnquake.c9users.io/
néanmoins, C9.io nous prend pas mal de temps à configurer et il serait très intéressant que vous installez mongodb sur votre PC afin de tester le code directement.

Tout l'avancement est mis sur le github, le nom des pull requests ainsi que des issues donne une idée sur ce quoi nous travaillons actuellement, si nous avons quelques problemes que ce soit nous vous tiendrons au courant.

Pour ce qui est de la réunion avec Mazen lors de sa venue à Evry, lors du dernier call nous vous avions dit avoir travailler sur les collisions. Il manque plus que son pull request @SisiLaFami 

Si possible, il serait intéressant de faire un point mardi tous ensemble avec vous monsieur Buffa, pour tous se retrouver et vous parlez de différentes idées :) 

Merci pour votre lecture.

Faouzy.
